# Generated by Django 6.0.1 on 2026-01-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_objeto3d_osso_objeto3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osso',
            name='objeto3D',
            field=models.FileField(blank=True, null=True, upload_to='modelo3D/'),
        ),
    ]
