# Generated by Django 6.0.1 on 2026-01-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_osso_objeto3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='osso',
            name='descricao',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
